services:
  api:
    build: ./backend
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      TMDB_API_KEY: "${TMDB_API_KEY}"
      API_BASE_URL: "${API_BASE_URL}"
      API_PORT: "${API_PORT}"
    depends_on:
      - db
  db:
    image: bitnami/postgresql:latest
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - moviesdb_pg_data:/bitnami/postgresql

volumes:
  moviesdb_pg_data:
